# Generated by Django 4.0.1 on 2022-01-14 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('books', '0001_initial'), ('books', '0002_alter_publication_book_cover_alter_publication_isbn_and_more'), ('books', '0003_alter_publication_author_alter_publication_language'), ('books', '0004_publication_birth_date_type'), ('books', '0005_rename_birth_date_type_publication_publication_date_type'), ('books', '0006_alter_publication_isbn'), ('books', '0007_alter_publication_publication_date_type')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('book_cover', models.URLField(blank=True, max_length=500, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.author')),
                ('publication_date_type', models.CharField(choices=[('Y', 'Tylko rok'), ('m.Y', 'Rok i miesiąc'), ('d.m.Y', 'Rok, miesiąc, dzień')], max_length=50)),
            ],
        ),
    ]
